language: go
go:
  - "1.12.x"
  - "1.13.x"
go_import_path: github.com/xen0n/go-workwx
branches:
  # https://bors.tech/documentation/getting-started/
  # unfortunately whitelisting is necessary because otherwise my own branches
  # would get (repeatedly) built as well...
  only:
    - 'staging'
    - 'trying'
    - 'develop'
    - 'master'
cache:
  - $GOPATH/pkg/dep
before_install:
  - export GO111MODULE=on
  - go get -u -v honnef.co/go/tools/cmd/staticcheck
install:
  - go install -v ./...
script:
  - ./ci/run-lint.sh
  - go test -v ./...
