language: go
go:
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"
go_import_path: github.com/61qt/go-workwx
branches:
  # https://bors.tech/documentation/getting-started/
  # unfortunately whitelisting is necessary because otherwise my own branches
  # would get (repeatedly) built as well...
  only:
    - 'staging'
    - 'trying'
    - 'develop'
    - 'master'
cache:
  - $HOME/.cache/go-build
  - $GOPATH/pkg/mod
before_install:
  - export GO111MODULE=on
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0
  - ./ci/run-lint.sh
install:
  - go install -v ./...
script:
  - go test -v ./...
